version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio-storage
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console Web
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
      MINIO_CONSOLE_ADDRESS: ":9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - ticket-network
    restart: unless-stopped

  # Cliente MinIO para configuração inicial
  minio-client:
    image: minio/mc:latest
    container_name: minio-client
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      echo 'Aguardando MinIO iniciar...';
      sleep 15;
      echo 'Configurando MinIO...';
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin123;
      /usr/bin/mc mb myminio/ticket-attachments --ignore-existing;
      /usr/bin/mc policy set download myminio/ticket-attachments;
      echo 'Configuração concluída!';
      exit 0;
      "
    networks:
      - ticket-network

volumes:
  minio_data:

networks:
  ticket-network:
    driver: bridge
